"""baseline detective schema

Revision ID: 5f8e4e1f3c64
Revises: 
Create Date: 2026-03-13 20:32:14.119600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f8e4e1f3c64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detective_campaign', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['slug'])
        batch_op.drop_column('intro_text')
        batch_op.drop_column('location')
        batch_op.drop_column('outro_text')

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('answer_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.create_unique_constraint('uq_detective_clue_campaign_order', ['campaign_id', 'order_index'])
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'])
        batch_op.drop_column('image_url')

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.create_unique_constraint('uq_detective_progress_user_campaign', ['user_id', 'campaign_id'])
        batch_op.create_foreign_key(None, 'detective_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'])
        batch_op.drop_column('skipped_orders')

    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_orders', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_detective_progress_user_campaign', type_='unique')
        batch_op.alter_column('is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('current_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_detective_clue_campaign_order', type_='unique')
        batch_op.alter_column('answer_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('detective_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outro_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intro_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
