"""user stats and achievement criteria

Revision ID: 6fa98531dd2f
Revises: a4b671342f12
Create Date: 2026-03-13 21:28:08.956552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa98531dd2f'
down_revision = 'a4b671342f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criteria_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('criteria_value', sa.Integer(), nullable=True))

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.drop_constraint('detective_clue_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'], referent_schema='detective')

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.drop_constraint('detective_progress_campaign_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('detective_progress_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detective_user', ['user_id'], ['id'], referent_schema='detective')
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'], referent_schema='detective')

    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_clues_solved', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('total_campaigns_completed', sa.Integer(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_constraint('user_achievement_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_achievement_achievement_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'detective_user', ['user_id'], ['id'], referent_schema='detective')
        batch_op.create_foreign_key(None, 'achievement', ['achievement_id'], ['id'], referent_schema='detective')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_achievement_achievement_id_fkey', 'achievement', ['achievement_id'], ['id'])
        batch_op.create_foreign_key('user_achievement_user_id_fkey', 'detective_user', ['user_id'], ['id'])

    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.drop_column('total_campaigns_completed')
        batch_op.drop_column('total_clues_solved')

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detective_progress_user_id_fkey', 'detective_user', ['user_id'], ['id'])
        batch_op.create_foreign_key('detective_progress_campaign_id_fkey', 'detective_campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('detective_clue_campaign_id_fkey', 'detective_campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_column('criteria_value')
        batch_op.drop_column('criteria_type')

    # ### end Alembic commands ###
