"""add achievements

Revision ID: a4b671342f12
Revises: 5f8e4e1f3c64
Create Date: 2026-03-13 21:01:17.819793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a4b671342f12'
down_revision = '5f8e4e1f3c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('badge_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='detective'
    )
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['detective.achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['detective.detective_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement_user_achievement'),
    schema='detective'
    )
    with op.batch_alter_table('detective_campaign', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('outro_text')
        batch_op.drop_column('intro_text')
        batch_op.drop_column('location')

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('answer_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('detective_clue_campaign_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'], referent_schema='detective')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('current_order',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('detective_progress_campaign_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('detective_progress_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'detective_user', ['user_id'], ['id'], referent_schema='detective')
        batch_op.create_foreign_key(None, 'detective_campaign', ['campaign_id'], ['id'], referent_schema='detective')
        batch_op.drop_column('skipped_orders')

    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detective_user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('detective_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skipped_orders', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detective_progress_user_id_fkey'), 'detective_user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('detective_progress_campaign_id_fkey'), 'detective_campaign', ['campaign_id'], ['id'])
        batch_op.alter_column('is_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('current_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detective_clue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('detective_clue_campaign_id_fkey'), 'detective_campaign', ['campaign_id'], ['id'])
        batch_op.alter_column('answer_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('detective_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('intro_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('outro_text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('user_achievement', schema='detective')
    op.drop_table('achievement', schema='detective')
    # ### end Alembic commands ###
